2024-05-22 13:00:43 [ERROR] log Internal Server Error: /
Traceback (most recent call last):
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_create' with keyword arguments '{'post_type1': 'news'}' not found. 1 pattern(s) tried: ['(?P<post_type>[^/]+)/create/\\Z']
2024-05-22 13:00:44 [ERROR] basehttp "GET / HTTP/1.1" 500 145
2024-05-22 13:12:31 [ERROR] log Internal Server Error: /
Traceback (most recent call last):
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
KeyError: 'url_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/kutak/SkillFactory/News_Portal/.venv/lib/python3.10/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'url_', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2024-05-22 13:12:32 [ERROR] basehttp "GET / HTTP/1.1" 500 145
